apiVersion: v1
kind: Secret
metadata:
  name: http-credentials
type: Opaque
data:
  user: cGF0cmljaw== #patrick
  password: bHVkbw== #ludo

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: foo
  labels:
    app: foo
spec:
  replicas: 1
  template:
    metadata:
      name: foo
      labels:
        app: foo
    spec:
      containers:
      - name: foo
        image: gcr.io/hackatoon-23052018/foo-service:7
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
          - name: HTTP_USER
            valueFrom:
              secretKeyRef:
                key: user
                name: http-credentials
          - name: HTTP_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: http-credentials
      restartPolicy: Always

  selector:
    matchLabels:
      app: foo

---

apiVersion: v1
kind: Service
metadata:
  name: foo-service
spec:
  selector:
    app: foo
  ports:
    - port: 8080
  type: LoadBalancer