apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bar
  labels:
    app: bar
spec:
  replicas: 3
  template:
    metadata:
      name: bar
      labels:
        app: bar
    spec:
      containers:
      - name: bar
        image: gcr.io/hackatoon-23052018/bar-service:2
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
      restartPolicy: Always

  selector:
    matchLabels:
      app: bar

---

apiVersion: v1
kind: Service
metadata:
  name: bar-service
spec:
  selector:
    app: bar
  ports:
    - port: 8080
  type: ClusterIP